// Generated by CoffeeScript 1.6.3
(function() {
  var Logger, logger;

  Logger = require('./logger');

  logger = new Logger();

  logger.Logger = Logger;

  logger.middleware = require('./middleware');

  module.exports = logger;

}).call(this);
