// Generated by CoffeeScript 1.6.3
(function() {
  var Logger, domain, logger, middleware;

  domain = require('domain');

  Logger = require('./logger');

  logger = new Logger({
    format: '%t - %s'
  });

  middleware = function(options) {
    var _middle;
    _middle = function(req, res, callback) {
      var dm;
      if (callback == null) {
        callback = function() {};
      }
      dm = domain.create();
      dm.add(req);
      dm.add(res);
      res.on('close', function() {
        return dm.dispose();
      });
      res.on('finish', function() {
        return dm.dispose();
      });
      dm.on('error', function(err) {
        dm.dispose();
        logger.err(err.stack);
        return process.exit(1);
      });
      process.on('uncaughtException', dm.intercept());
      return dm.run(callback);
    };
    return _middle;
  };

  module.exports = middleware;

}).call(this);
